
version: '2.1'

networks:
  hyperiot:
    name: hyperiot
    driver: bridge

services:

  zookeeper:
    extends:
     file: docker-compose-svil-basic.yml
     service: zookeeper

  postgresql:
    extends:
     file: docker-compose-svil-basic.yml
     service: postgresql

  kafka:
    extends:
     file: docker-compose-svil-basic.yml
     service: kafka
    depends_on:
       - zookeeper
