version: '2.1'

networks:
  hyperiot:
    name: hyperiot
    driver: bridge

services:
  zookeeper:
    extends:
     file: docker-compose-svil-basic.yml
     service: zookeeper

  kafka:
    extends:
     file: docker-compose-svil-basic.yml
     service: kafka
    depends_on:
       - zookeeper

  nimbus:
    extends:
     file: docker-compose-svil-basic.yml
     service: nimbus
    links:
      - zookeeper
    depends_on:
      - zookeeper

  supervisor:
    extends:
     file: docker-compose-svil-basic.yml
     service: supervisor
    links:
      - zookeeper
      - nimbus

  storm-ui:
    extends:
     file: docker-compose-svil-basic.yml
     service: storm-ui
    links:
      - nimbus
    depends_on:
      - supervisor
      - nimbus

  postgresql:
    extends:
     file: docker-compose-svil-basic.yml
     service: postgresql

  namenode:
    extends:
     file: docker-compose-svil-basic.yml
     service: namenode

  datanode1:
    extends:
     file: docker-compose-svil-basic.yml
     service: datanode1
    depends_on:
      - "namenode"
    links:
      - "namenode"

  datanode2:
    extends:
     file: docker-compose-svil-basic.yml
     service: datanode2
    depends_on:
      - "namenode"
    links:
      - "namenode"

  datanode3:
    extends:
     file: docker-compose-svil-basic.yml
     service: datanode3
    depends_on:
      - "namenode"
    links:
      - "namenode"

  hbase-master:
    extends:
     file: docker-compose-svil-basic.yml
     service: hbase-master

  hbase-region:
    extends:
     file: docker-compose-svil-basic.yml
     service: hbase-region
    depends_on:
      - hbase-master
     
  spark-master:
    extends:
     file: docker-compose-svil-basic.yml
     service: spark-master
    depends_on:
      - "namenode"
    links:
      - "namenode"
      
  spark-worker-1:
    extends:
     file: docker-compose-svil-basic.yml
     service: spark-worker-1
    depends_on:
      - "spark-master"
    links:
      - "spark-master"
