# Topology configuration
name: "topology-869-870"
config:
  topology.workers: 1
  spout.kafka_servers: "${spout.kafka_servers}"
  bolt.enrichment.kafka_topic: "${bolt.enrichment.kafka_topic}"
  bolt.enrichment.drools: ${bolt.enrichment.drools}
  bolt.event.kafka_topic: "${bolt.event.kafka_topic}"
  bolt.event.drools: ${bolt.event.drools}
  packet.870: ${packet.870}
  spout.kafka_topic.870: "${spout.kafka_topic.870}"
  hbase.conf:
    hbase.rootdir: "${hbase.rootdir}"
    hbase.zookeeper.quorum: "${hbase.zookeeper.quorum}"
    hbase.zookeeper.property.clientPort: "${hbase.zookeeper.property.clientPort}"

components:
  # KAFKA Spout
  - id: "spoutConfigBuilder-raw-870"
    className: "org.apache.storm.kafka.spout.KafkaSpoutConfig$Builder"
    constructorArgs:
      - "${spout.kafka_servers}"
      - ["${spout.kafka_topic.870}"]
    configMethods:
      - name: "setProp"
        args:
          - {
            "key.deserializer" : "org.apache.kafka.common.serialization.StringDeserializer",
            "value.deserializer": "org.apache.kafka.common.serialization.StringDeserializer",
            "group.id" : "group-1"
          }
  - id: "spoutConfig-raw-870"
    className: "org.apache.storm.kafka.spout.KafkaSpoutConfig"
    constructorArgs:
      - ref: "spoutConfigBuilder-raw-870"


  # Kafka producer for enriched packets (speed-layer)
  - id: "boltConfig-speedlayer-topic"
    className: "org.apache.storm.kafka.bolt.selector.DefaultTopicSelector"
    constructorArgs:
      - "${bolt.enrichment.kafka_topic}"
  - id: "boltConfig-speedlayer-mapper"
    className: "org.apache.storm.kafka.bolt.mapper.FieldNameBasedTupleToKafkaMapper"
    constructorArgs:
      - "device_id"
      - "packet"
  - id: "boltConfig-speedlayer"
    className: "java.util.Properties"
    configMethods:
      - name: "put"
        args:
          - "bootstrap.servers"
          - "${spout.kafka_servers}"
      - name: "put"
        args:
          - "acks"
          - "1"
      - name: "put"
        args:
          - "key.serializer"
          - "org.apache.kafka.common.serialization.LongSerializer"
      - name: "put"
        args:
          - "value.serializer"
          - "it.acsoftware.hyperiot.avro.AvroSerializer"

  # Kafka producer for packet events (event-layer)
  - id: "boltConfig-eventlayer-topic"
    className: "org.apache.storm.kafka.bolt.selector.DefaultTopicSelector"
    constructorArgs:
      - "${bolt.event.kafka_topic}"
  - id: "boltConfig-eventlayer-mapper"
    className: "org.apache.storm.kafka.bolt.mapper.FieldNameBasedTupleToKafkaMapper"
    constructorArgs:
      - "message_type"
      - "event_json"
  - id: "boltConfig-eventlayer"
    className: "java.util.Properties"
    configMethods:
      - name: "put"
        args:
          - "bootstrap.servers"
          - "${spout.kafka_servers}"
      - name: "put"
        args:
          - "acks"
          - "1"
      - name: "put"
        args:
          - "key.serializer"
          - "org.apache.kafka.common.serialization.StringSerializer"
      - name: "put"
        args:
          - "value.serializer"
          - "org.apache.kafka.common.serialization.StringSerializer"

  # HDFS components
  - id: "syncPolicy"
    className: "org.apache.storm.hdfs.bolt.sync.CountSyncPolicy"
    constructorArgs:
      - 10
  - id: "rotationPolicy"
    className: "org.apache.storm.hdfs.bolt.rotation.FileSizeRotationPolicy"
    constructorArgs:
      - 1.0
      - GB
  - id: "fileNameFormat"
    className: "org.apache.storm.hdfs.bolt.format.DefaultFileNameFormat"
    configMethods:
      - name: "withPath"
        args: ["${hdfs.write.dir}"]
      - name: "withExtension"
        args: [".avro"]
  # rotation action not implemented yet
#  - id: "rotationAction"
#    className: "org.apache.storm.hdfs.common.rotation.MoveFileAction"
#    configMethods:
#      - name: "toDestination"
#        args: ["${hdfs.dest.dir}"]
  #HDFS partitioners
  - id: "dayPartitioner"
    className: "it.acsoftware.hyperiot.storm.hdfs.partitioner.HyperiotPartitioner"
    configMethods:
      - name: "withDepth"
        args: ["day"]
  - id: "hourPartitioner"
    className: "it.acsoftware.hyperiot.storm.hdfs.partitioner.HyperiotPartitioner"
    configMethods:
      - name: "withDepth"
        args: ["hour"]
  - id: "monthPartitioner"
    className: "it.acsoftware.hyperiot.storm.hdfs.partitioner.HyperiotPartitioner"
    configMethods:
      - name: "withDepth"
        args: ["month"]
  - id: "quarterPartitioner"
    className: "it.acsoftware.hyperiot.storm.hdfs.partitioner.HyperiotPartitioner"
    configMethods:
      - name: "withDepth"
        args: ["quarter"]
  - id: "semesterPartitioner"
    className: "it.acsoftware.hyperiot.storm.hdfs.partitioner.HyperiotPartitioner"
    configMethods:
      - name: "withDepth"
        args: ["semester"]
  - id: "yearPartitioner"
    className: "it.acsoftware.hyperiot.storm.hdfs.partitioner.HyperiotPartitioner"
    configMethods:
      - name: "withDepth"
        args: ["year"]

  # HBase components
  - id: "columnFields"
    className: "org.apache.storm.tuple.Fields"
    constructorArgs:
      - ["packet"]
  - id: "mapper"
    className: "org.apache.storm.hbase.bolt.mapper.SimpleHBaseMapper"
    configMethods:
      - name: "withRowKeyField"
        args: ["rowKey"]
      - name: "withColumnFields"
        args: [ref: "columnFields"]
      - name: "withColumnFamily"
        args: ["hpacket"]

# Spout definitions
spouts:
  # Kafka raw messages spout
  - id: "kafka-spout-raw-870"
    className: "org.apache.storm.kafka.spout.KafkaSpout"
    constructorArgs:
      - ref: "spoutConfig-raw-870"


# Bolt definitions
bolts:
  - id: "bolt-deserialization"
    className: "it.acsoftware.hyperiot.storm.runtime.bolt.DeserializationBolt"
  - id: "bolt-enrichment"
    className: "it.acsoftware.hyperiot.storm.runtime.bolt.EnrichmentBolt"
  - id: "bolt-event"
    className: "it.acsoftware.hyperiot.storm.runtime.bolt.EventBolt"
  - id: "bolt-kafka-speedlayer"
    className: "org.apache.storm.kafka.bolt.KafkaBolt"
    configMethods:
      - name: "withProducerProperties"
        args: [ref: "boltConfig-speedlayer"]
      - name: "withTopicSelector"
        args: [ref: "boltConfig-speedlayer-topic"]
      - name: "withTupleToKafkaMapper"
        args: [ref: "boltConfig-speedlayer-mapper"]
  - id: "bolt-kafka-eventlayer"
    className: "org.apache.storm.kafka.bolt.KafkaBolt"
    configMethods:
      - name: "withProducerProperties"
        args: [ref: "boltConfig-eventlayer"]
      - name: "withTopicSelector"
        args: [ref: "boltConfig-eventlayer-topic"]
      - name: "withTupleToKafkaMapper"
        args: [ref: "boltConfig-eventlayer-mapper"]
  - id: "bolt-selection"
    className: "it.acsoftware.hyperiot.storm.runtime.bolt.SelectionBolt"
# valuta se per ogni bolt hdfs inserire il serializer KRYO
# https://github.com/apache/storm/tree/master/external/storm-hdfs#hdfs-bolt
  - id: "bolt-hyperiot-hour"
    className: "org.apache.storm.hdfs.bolt.AvroGenericRecordBolt"
    configMethods:
      - name: "withConfigKey"
        args: ["hdfs.config-1"]
      - name: "withFsUrl"
        args: ["${hdfs.url}"]
      - name: "withFileNameFormat"
        args: [ref: "fileNameFormat"]
      - name: "withRotationPolicy"
        args: [ref: "rotationPolicy"]
      - name: "withSyncPolicy"
        args: [ref: "syncPolicy"]
      - name: "withPartitioner"
        args: [ref: "hourPartitioner"]
  - id: "bolt-hyperiot-quarter"
    className: "org.apache.storm.hdfs.bolt.AvroGenericRecordBolt"
    configMethods:
      - name: "withConfigKey"
        args: ["hdfs.config-1"]
      - name: "withFsUrl"
        args: ["${hdfs.url}"]
      - name: "withFileNameFormat"
        args: [ref: "fileNameFormat"]
      - name: "withRotationPolicy"
        args: [ref: "rotationPolicy"]
      - name: "withSyncPolicy"
        args: [ref: "syncPolicy"]
      - name: "withPartitioner"
        args: [ref: "quarterPartitioner"]
  - id: "bolt-hyperiot-semester"
    className: "org.apache.storm.hdfs.bolt.AvroGenericRecordBolt"
    configMethods:
      - name: "withConfigKey"
        args: ["hdfs.config-1"]
      - name: "withFsUrl"
        args: ["${hdfs.url}"]
      - name: "withFileNameFormat"
        args: [ref: "fileNameFormat"]
      - name: "withRotationPolicy"
        args: [ref: "rotationPolicy"]
      - name: "withSyncPolicy"
        args: [ref: "syncPolicy"]
      - name: "withPartitioner"
        args: [ref: "semesterPartitioner"]
  - id: "bolt-hyperiot-year"
    className: "org.apache.storm.hdfs.bolt.AvroGenericRecordBolt"
    configMethods:
      - name: "withConfigKey"
        args: ["hdfs.config-1"]
      - name: "withFsUrl"
        args: ["${hdfs.url}"]
      - name: "withFileNameFormat"
        args: [ref: "fileNameFormat"]
      - name: "withRotationPolicy"
        args: [ref: "rotationPolicy"]
      - name: "withSyncPolicy"
        args: [ref: "syncPolicy"]
      - name: "withPartitioner"
        args: [ref: "yearPartitioner"]
  - id: "bolt-hyperiot-month"
    className: "org.apache.storm.hdfs.bolt.AvroGenericRecordBolt"
    configMethods:
      - name: "withConfigKey"
        args: ["hdfs.config-1"]
      - name: "withFsUrl"
        args: ["${hdfs.url}"]
      - name: "withFileNameFormat"
        args: [ref: "fileNameFormat"]
      - name: "withRotationPolicy"
        args: [ref: "rotationPolicy"]
      - name: "withSyncPolicy"
        args: [ref: "syncPolicy"]
      - name: "withPartitioner"
        args: [ref: "monthPartitioner"]
  - id: "bolt-hyperiot-day"
    className: "org.apache.storm.hdfs.bolt.AvroGenericRecordBolt"
    configMethods:
      - name: "withConfigKey"
        args: ["hdfs.config-1"]
      - name: "withFsUrl"
        args: ["${hdfs.url}"]
      - name: "withFileNameFormat"
        args: [ref: "fileNameFormat"]
      - name: "withRotationPolicy"
        args: [ref: "rotationPolicy"]
      - name: "withSyncPolicy"
        args: [ref: "syncPolicy"]
      - name: "withPartitioner"
        args: [ref: "dayPartitioner"]
  
  #HBase bolt
  - id: "hbase-bolt"
    className: "org.apache.storm.hbase.bolt.HBaseBolt"
    constructorArgs:
      - "giacomo" # HBase table name
      - ref: "mapper"
    configMethods:
      - name: "withConfigKey"
        args: ["hbase.conf"]
#    parallelism: 1

# Stream definitions
streams:
  # From Kafka raw messages spout (kafka-spout-raw) to deserialization bolt (bolt-deserialization)
  - name: "kafka-spout-raw-870 --> bolt-deserialization"
    from: "kafka-spout-raw-870"
    to: "bolt-deserialization"
    grouping:
      type: SHUFFLE

  # From deserialization bolt (bolt-deserialization) to enrichment bolt (bolt-enrichment)
  - name: "bolt-deserialization --> bolt-enrichment"
    from: "bolt-deserialization"
    to: "bolt-enrichment"
    grouping:
      type: SHUFFLE
  # From deserialization bolt (bolt-deserialization) to event bolt (bolt-event)
  - name: "bolt-deserialization --> bolt-event"
    from: "bolt-deserialization"
    to: "bolt-event"
    grouping:
      type: SHUFFLE
  # From enrichment bolt (bolt-enrichment) to speed-layer bolt (bolt-kafka-speedlayer) (sending back to enriched kafka topic using AVRO schema)
  - name: "bolt-enrichment --> bolt-kafka-speedlayer"
    from: "bolt-enrichment"
    to: "bolt-kafka-speedlayer"
    grouping:
      type: SHUFFLE
  # From event bolt (bolt-event) to event-layer bolt (bolt-kafka-eventlayer) (sending back to kafka event topic sending JSON formatted event action)
  - name: "bolt-event --> bolt-kafka-eventlayer"
    from: "bolt-event"
    to: "bolt-kafka-eventlayer"
    grouping:
      type: SHUFFLE
  # From enrichment bolt (bolt-enrichment) to selection-bolt
  - name : "bolt-enrichment --> bolt-selection"
    from: "bolt-enrichment"
    to: "bolt-selection"
    grouping:
      type: SHUFFLE
  # From selection bolt (bolt-selection) to bolt-hyperiot-hour
  - name : "bolt-selection --> bolt-hyperiot-hour"
    from: "bolt-selection"
    to: "bolt-hyperiot-hour"
    grouping:
      type: SHUFFLE
      streamId: "hour"
  # From selection bolt (bolt-selection) to bolt-hyperiot-quarter
  - name : "bolt-selection --> bolt-hyperiot-quarter"
    from: "bolt-selection"
    to: "bolt-hyperiot-quarter"
    grouping:
      type: SHUFFLE
      streamId: "quarter"
  # From selection bolt (bolt-selection) to bolt-hyperiot-semester
  - name : "bolt-selection --> bolt-hyperiot-semester"
    from: "bolt-selection"
    to: "bolt-hyperiot-semester"
    grouping:
      type: SHUFFLE
      streamId: "semester"
  # From selection bolt (bolt-selection) to bolt-hyperiot-year
  - name : "bolt-selection --> bolt-hyperiot-year"
    from: "bolt-selection"
    to: "bolt-hyperiot-year"
    grouping:
      type: SHUFFLE
      streamId: "year"
  # From selection bolt (bolt-selection) to bolt-hyperiot-month
  - name : "bolt-selection --> bolt-hyperiot-month"
    from: "bolt-selection"
    to: "bolt-hyperiot-month"
    grouping:
      type: SHUFFLE
      streamId: "month"
  # From selection bolt (bolt-selection) to bolt-hyperiot-day
  - name : "bolt-selection --> bolt-hyperiot-day"
    from: "bolt-selection"
    to: "bolt-hyperiot-day"
    grouping:
      type: SHUFFLE
      streamId: "day"
  #From selection bolt (bolt-selection) to hbase bolt (hbase-bolt)
  - name: "bolt-selection --> hbase-bolt"
    from: "bolt-selection"
    to: "hbase-bolt"
    grouping:
      type: SHUFFLE
      streamId: "hbase"
  

