FROM alpine:3.20.0


################################
# Karaf HyperIoT Microservices #
################################

ARG KARAF_MICROSERVICES_VERSION=1.0.0

ENV KARAF_USER karaf
ENV KARAF_UID 8181
#ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV KARAF_VERSION 4.2.6
ENV JAVA_MAX_MEM 256m
ENV KARAF_EXEC exec
ENV KARAF_FOLDER /opt/apache-karaf-microservices
ENV KARAF_TAR_FILE karaf-microservices-${KARAF_MICROSERVICES_VERSION}.tar.gz
ENV DB_SERVER_NAME host.docker.internal
ENV DB_SERVER_PORT 5432
ENV DB_SERVER_USER hyperiot
ENV DB_SERVER_PASSWORD hyperiot
ENV DB_SERVER_JDBC_DRIVER org.postgresql.Driver
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=/usr/lib/jvm/java-17-openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# --- Installing required packages ---
RUN apk update && apk add --no-cache openjdk17 java-cacerts jq curl
# --- Extracting Karaf ---
COPY ./target/$KARAF_TAR_FILE /opt/
RUN mkdir /opt/karaf
RUN addgroup -g $KARAF_UID -S $KARAF_USER && adduser -u $KARAF_UID -G $KARAF_USER -S -D $KARAF_USER
RUN tar --strip-components=1 -C /opt/karaf -xzf /opt/$KARAF_TAR_FILE \
    && rm /opt/$KARAF_TAR_FILE \
    && chown -R $KARAF_USER:$KARAF_USER /opt/karaf \
    && chmod 700 /opt/karaf/data
RUN rm -rf /opt/karaf/system/it
# -----------------------------------
EXPOSE 1099 8101 44444 8181 1883 61616 61614
USER $KARAF_USER
CMD ["/opt/karaf/bin/karaf", "run","debug","clean"]

